anime=input('digite algo')
print('O tipo primitivo desse valor é {}',format(type(anime)))
print('So tem espaços? {}',format(anime.isspace()))
print('é um nùmero?{}',format(anime.isnumeric()))
print('é alfabético?{}',format(anime.isalpha()))
print('é alfanumérico?{}',format(anime.isalnum()))
print('estar em maiúsculas?{}',format(anime.isupper()))
print('estar em minúsculas?{}',format(anime.islower()))
print('está em capitalizada?{}',format(anime.istitle()))

